ruby_web:
 image: 10.65.57.126:5000/ruby-mysql-web:0.0.1-SNAPSHOT 
 environment:
  PORT: 9595
 ports:
  - "9595:9595"
 links:
  - mysql_db:mysql_host
mysql_db:
 image: mysql:latest
 volumes:
 - /mnt/mysql_data_prod_clone:/var/lib/mysql
 environment:
  MYSQL_ROOT_PASSWORD: netapp01
